"""Walmart product content extraction helpers.

This module intentionally extracts only structured product PDP data. It does not
create summaries, rewrite bullets, collect UI assets, or pull variation/swatch
image galleries.
"""

from __future__ import annotations

import html as html_lib
import json
import re
from typing import Any, Iterable
from urllib.parse import urlparse

import requests
from bs4 import BeautifulSoup


BASE_COLUMNS = ["SKU", "Walmart URL", "Walmart Item ID", "Status", "Error"]

FIELD_DEFINITIONS = [
    ("title", "Title"),
    ("brand", "Brand"),
    ("price", "Price"),
    ("currency", "Currency"),
    ("seller", "Seller"),
    ("availability", "Availability"),
    ("rating", "Rating"),
    ("review_count", "Review Count"),
    ("main_image", "Main Image"),
    ("additional_images", "Additional Images"),
    ("bullet_points", "Original PDP Bullet Points"),
    ("description", "Original PDP Description"),
    ("specifications", "Specifications"),
    ("ingredients", "Ingredients"),
    ("warnings", "Warnings"),
    ("category", "Category / Breadcrumbs"),
    ("upc_gtin", "UPC / GTIN"),
    ("model", "Model / Part Number"),
]

FIELD_LABELS = dict(FIELD_DEFINITIONS)
FIELD_KEYS = [key for key, _ in FIELD_DEFINITIONS]

DEFAULT_HEADERS = {
    "User-Agent": (
        "Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
        "AppleWebKit/537.36 (KHTML, like Gecko) "
        "Chrome/124.0 Safari/537.36"
    ),
    "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
    "Accept-Language": "en-US,en;q=0.9",
    "Cache-Control": "no-cache",
    "Pragma": "no-cache",
}

BLOCK_TEXT_PATTERNS = (
    "robot or human",
    "verify your identity",
    "temporarily blocked",
    "unusual traffic",
    "captcha",
    "access denied",
)

FORBIDDEN_PATH_TERMS = (
    "variant",
    "variants",
    "swatch",
    "swatches",
    "review",
    "reviews",
    "ratingstars",
    "sponsored",
    "ads",
)

AI_PATH_TERMS = (
    "ai",
    "genai",
    "generatedsummary",
    "generated_summary",
    "reviewsummary",
    "summaryfromreviews",
    "summarized",
)

AI_TEXT_PATTERNS = (
    "ai-generated",
    "ai generated",
    "generated by ai",
    "customer review summary",
    "summary of reviews",
    "review summary",
)

IMAGE_BAD_PATH_TERMS = (
    "badge",
    "logo",
    "icon",
    "sprite",
    "rating",
    "star",
    "review",
    "avatar",
    "swatch",
    "variant",
    "seller",
    "fulfillment",
)

IMAGE_BAD_EXTENSIONS = (".png", ".svg", ".gif", ".ico", ".bmp")
IMAGE_GOOD_EXTENSIONS = (".jpg", ".jpeg", ".webp", ".jfif")


class ScrapeError(Exception):
    """Internal scrape error used to classify extraction failures."""


def is_valid_walmart_url(url: str) -> bool:
    parsed = urlparse(str(url).strip())
    return parsed.scheme in {"http", "https"} and "walmart.com" in parsed.netloc.lower()


def extract_item_id(url: str) -> str:
    match = re.search(r"/ip/(?:[^/]+/)?(\d+)", str(url))
    return match.group(1) if match else ""


def compact_spaces(text: str) -> str:
    return re.sub(r"\s+", " ", text).strip()


def looks_like_ai_text(text: str) -> bool:
    low = compact_spaces(text).lower()
    return any(pattern in low for pattern in AI_TEXT_PATTERNS)


def path_has_terms(path: Iterable[str], terms: Iterable[str]) -> bool:
    joined = "/".join(str(p).lower().replace("-", "").replace("_", "") for p in path)
    return any(term.replace("-", "").replace("_", "") in joined for term in terms)


def clean_text(value: Any) -> str:
    """Return readable text without rewriting or summarizing content."""
    if value is None:
        return ""

    if isinstance(value, (int, float)):
        return str(value)

    if isinstance(value, list):
        parts = [clean_text(item) for item in value]
        return compact_spaces(" | ".join(part for part in parts if part))

    if isinstance(value, dict):
        # Avoid dumping arbitrary JSON into content columns.
        for key in ("name", "displayName", "label", "value", "text", "description"):
            if key in value:
                return clean_text(value.get(key))
        return ""

    text = html_lib.unescape(str(value)).replace("\\u0026", "&")
    if "<" in text and ">" in text:
        soup = BeautifulSoup(text, "html.parser")
        for tag in soup(["script", "style", "noscript"]):
            tag.decompose()
        text = soup.get_text(" ", strip=True)

    text = compact_spaces(text)
    if looks_like_ai_text(text):
        return ""
    return text


def html_to_lines(value: Any) -> list[str]:
    """Extract original line/list text from a PDP HTML field."""
    if value is None:
        return []

    if isinstance(value, list):
        lines: list[str] = []
        for item in value:
            lines.extend(html_to_lines(item))
        return unique_keep_order(lines)

    if isinstance(value, dict):
        return html_to_lines(clean_text(value))

    raw = html_lib.unescape(str(value)).replace("\\u0026", "&")
    if not raw.strip():
        return []

    if "<" in raw and ">" in raw:
        soup = BeautifulSoup(raw, "html.parser")
        for tag in soup(["script", "style", "noscript"]):
            tag.decompose()

        li_lines = [clean_text(li.get_text(" ", strip=True)) for li in soup.find_all("li")]
        li_lines = [line for line in li_lines if line]
        if li_lines:
            return unique_keep_order(li_lines)

        block_lines: list[str] = []
        for tag in soup.find_all(["p", "div"]):
            if tag.find(["p", "div", "li"]):
                continue
            text = clean_text(tag.get_text(" ", strip=True))
            if text:
                block_lines.append(text)
        if block_lines:
            return unique_keep_order(block_lines)

        fallback = clean_text(soup.get_text(" ", strip=True))
        return [fallback] if fallback else []

    # Non-HTML text. Preserve existing line boundaries where present.
    pieces = re.split(r"[\r\n]+", raw)
    lines = [clean_text(piece) for piece in pieces]
    return unique_keep_order([line for line in lines if line])


def unique_keep_order(values: Iterable[str]) -> list[str]:
    seen: set[str] = set()
    output: list[str] = []
    for value in values:
        item = compact_spaces(str(value))
        if not item:
            continue
        key = item.lower()
        if key not in seen:
            seen.add(key)
            output.append(item)
    return output


def as_list(value: Any) -> list[Any]:
    if value is None:
        return []
    if isinstance(value, list):
        return value
    return [value]


def dig(obj: Any, path: Iterable[str]) -> Any:
    current = obj
    for part in path:
        if not isinstance(current, dict) or part not in current:
            return None
        current = current[part]
    return current


def parse_json_safely(text: str) -> Any | None:
    try:
        return json.loads(text)
    except Exception:
        return None


def load_page_json(soup: BeautifulSoup) -> tuple[Any | None, list[dict[str, Any]]]:
    """Return Next.js JSON and JSON-LD Product objects."""
    next_data = None
    next_script = soup.find("script", id="__NEXT_DATA__")
    if next_script:
        text = next_script.string or next_script.get_text() or ""
        next_data = parse_json_safely(text.strip())

    json_ld_products: list[dict[str, Any]] = []
    for script in soup.find_all("script", attrs={"type": "application/ld+json"}):
        text = script.string or script.get_text() or ""
        data = parse_json_safely(text.strip())
        for item in flatten_json_ld(data):
            if isinstance(item, dict):
                item_type = item.get("@type") or item.get("type") or ""
                if isinstance(item_type, list):
                    item_type = " ".join(str(x) for x in item_type)
                if "product" in str(item_type).lower():
                    json_ld_products.append(item)

    return next_data, json_ld_products


def flatten_json_ld(data: Any) -> list[Any]:
    if data is None:
        return []
    if isinstance(data, list):
        result: list[Any] = []
        for item in data:
            result.extend(flatten_json_ld(item))
        return result
    if isinstance(data, dict):
        result = [data]
        for key in ("@graph", "graph", "itemListElement"):
            if key in data:
                result.extend(flatten_json_ld(data[key]))
        return result
    return []


def iter_dicts(obj: Any, path: tuple[str, ...] = ()) -> Iterable[tuple[tuple[str, ...], dict[str, Any]]]:
    if isinstance(obj, dict):
        yield path, obj
        for key, value in obj.items():
            yield from iter_dicts(value, path + (str(key),))
    elif isinstance(obj, list):
        for index, value in enumerate(obj):
            yield from iter_dicts(value, path + (str(index),))


def score_product_object(obj: dict[str, Any]) -> int:
    keys = set(obj.keys())
    score = 0
    if keys.intersection({"usItemId", "productId", "productID", "itemId", "id"}):
        score += 5
    if keys.intersection({"name", "title", "productName"}):
        score += 5
    if "imageInfo" in keys or "images" in keys or "image" in keys:
        score += 4
    if "priceInfo" in keys or "price" in keys or "offers" in keys:
        score += 4
    if keys.intersection({"shortDescription", "longDescription", "description", "keyFeatures"}):
        score += 3
    if keys.intersection({"averageRating", "numberOfReviews", "aggregateRating"}):
        score += 2
    if keys.intersection({"specifications", "productSpecifications"}):
        score += 2
    return score


def find_product_object(next_data: Any) -> dict[str, Any]:
    if not isinstance(next_data, dict):
        return {}

    direct_paths = [
        ("props", "pageProps", "initialData", "data", "product"),
        ("props", "pageProps", "initialData", "product"),
        ("props", "pageProps", "product"),
        ("props", "pageProps", "data", "product"),
        ("pageProps", "initialData", "data", "product"),
    ]
    for path in direct_paths:
        value = dig(next_data, path)
        if isinstance(value, dict) and score_product_object(value) >= 8:
            return value

    best: tuple[int, int, dict[str, Any]] | None = None
    for path, obj in iter_dicts(next_data):
        if path_has_terms(path, ("variant", "swatch", "reviews", "sponsored")):
            continue
        score = score_product_object(obj)
        if score >= 10:
            size_hint = len(json.dumps(obj, default=str))
            candidate = (score, size_hint, obj)
            if best is None or candidate[:2] > best[:2]:
                best = candidate

    return best[2] if best else {}


def first_value(obj: dict[str, Any], keys: Iterable[str]) -> Any:
    for key in keys:
        if key in obj and obj[key] not in (None, "", [], {}):
            return obj[key]
    return None


def recursive_key_values(
    obj: Any,
    wanted_key_parts: Iterable[str],
    path: tuple[str, ...] = (),
    skip_forbidden: bool = True,
) -> Iterable[tuple[tuple[str, ...], str, Any]]:
    wanted = tuple(part.lower() for part in wanted_key_parts)
    if skip_forbidden and (path_has_terms(path, FORBIDDEN_PATH_TERMS) or path_has_terms(path, AI_PATH_TERMS)):
        return

    if isinstance(obj, dict):
        for key, value in obj.items():
            key_str = str(key)
            low = key_str.lower().replace("_", "").replace("-", "")
            new_path = path + (key_str,)
            if any(part in low for part in wanted):
                yield new_path, key_str, value
            yield from recursive_key_values(value, wanted, new_path, skip_forbidden=skip_forbidden)
    elif isinstance(obj, list):
        for index, value in enumerate(obj):
            yield from recursive_key_values(value, wanted, path + (str(index),), skip_forbidden=skip_forbidden)


def normalize_price(value: Any) -> str:
    if value is None:
        return ""
    if isinstance(value, dict):
        for key in ("price", "priceString", "displayPrice", "value", "amount"):
            result = normalize_price(value.get(key))
            if result:
                return result
        return ""
    text = clean_text(value)
    if not text:
        return ""
    match = re.search(r"\$?\s*([0-9]+(?:,[0-9]{3})*(?:\.[0-9]{1,2})?)", text)
    return match.group(1).replace(",", "") if match else text


def extract_price(product: dict[str, Any], json_ld: dict[str, Any]) -> str:
    price_info = product.get("priceInfo")
    if isinstance(price_info, dict):
        for path in (
            ("currentPrice", "price"),
            ("currentPrice", "priceString"),
            ("linePrice",),
            ("wasPrice", "price"),
            ("comparisonPrice", "price"),
        ):
            result = normalize_price(dig(price_info, path))
            if result:
                return result

    for key in ("price", "salePrice", "currentPrice"):
        result = normalize_price(product.get(key))
        if result:
            return result

    offers = json_ld.get("offers") if isinstance(json_ld, dict) else None
    for offer in as_list(offers):
        if isinstance(offer, dict):
            result = normalize_price(offer.get("price") or offer.get("lowPrice"))
            if result:
                return result
    return ""


def extract_currency(product: dict[str, Any], json_ld: dict[str, Any]) -> str:
    price_info = product.get("priceInfo")
    if isinstance(price_info, dict):
        for path in (("currentPrice", "currencyUnit"), ("currentPrice", "currency"), ("currencyUnit",)):
            text = clean_text(dig(price_info, path))
            if text:
                return text
    offers = json_ld.get("offers") if isinstance(json_ld, dict) else None
    for offer in as_list(offers):
        if isinstance(offer, dict):
            text = clean_text(offer.get("priceCurrency"))
            if text:
                return text
    return ""


def extract_seller(product: dict[str, Any], json_ld: dict[str, Any]) -> str:
    for key in ("sellerName", "sellerDisplayName", "soldBy", "merchantName"):
        text = clean_text(product.get(key))
        if text:
            return text

    seller_info = product.get("sellerInfo") or product.get("seller")
    if isinstance(seller_info, dict):
        for key in ("name", "sellerName", "displayName", "sellerDisplayName"):
            text = clean_text(seller_info.get(key))
            if text:
                return text

    offers = json_ld.get("offers") if isinstance(json_ld, dict) else None
    for offer in as_list(offers):
        if isinstance(offer, dict):
            seller = offer.get("seller")
            if isinstance(seller, dict):
                text = clean_text(seller.get("name"))
                if text:
                    return text
    return ""


def extract_availability(product: dict[str, Any], json_ld: dict[str, Any], page_text: str) -> str:
    for key in ("availabilityStatus", "availability", "stockStatus"):
        text = clean_text(product.get(key))
        if text:
            return text

    offers = json_ld.get("offers") if isinstance(json_ld, dict) else None
    for offer in as_list(offers):
        if isinstance(offer, dict):
            text = clean_text(offer.get("availability"))
            if text:
                return text.rsplit("/", 1)[-1]

    low = page_text.lower()
    if "out of stock" in low:
        return "Out of stock"
    if "add to cart" in low:
        return "Available"
    return ""


def extract_rating(product: dict[str, Any], json_ld: dict[str, Any]) -> tuple[str, str]:
    rating = clean_text(first_value(product, ("averageRating", "rating", "ratingValue")))
    review_count = clean_text(first_value(product, ("numberOfReviews", "reviewCount", "reviewsCount")))

    aggregate = json_ld.get("aggregateRating") if isinstance(json_ld, dict) else None
    if isinstance(aggregate, dict):
        rating = rating or clean_text(aggregate.get("ratingValue"))
        review_count = review_count or clean_text(aggregate.get("reviewCount") or aggregate.get("ratingCount"))

    return rating, review_count


def normalize_image_url(url: Any) -> str:
    text = html_lib.unescape(str(url or "")).strip()
    text = text.replace("\\u002F", "/").replace("\\/", "/")
    if text.startswith("//"):
        text = "https:" + text
    return text


def is_product_image_url(url: str) -> bool:
    if not url:
        return False
    parsed = urlparse(url)
    if parsed.scheme not in {"http", "https"}:
        return False
    netloc = parsed.netloc.lower()
    if "walmartimages.com" not in netloc:
        return False

    path = parsed.path.lower()
    if any(term in path for term in IMAGE_BAD_PATH_TERMS):
        return False
    if path.endswith(IMAGE_BAD_EXTENSIONS):
        return False
    if not path.endswith(IMAGE_GOOD_EXTENSIONS):
        return False

    # Most Walmart PDP product photos are stored below /asr/ or /seo/.
    # This prevents UI assets from being mixed into the image output.
    if "/asr/" not in path and "/seo/" not in path:
        return False
    return True


def collect_image_urls_from_image_info(image_info: Any) -> list[str]:
    urls: list[str] = []

    def add(value: Any, image_meta: dict[str, Any] | None = None) -> None:
        if image_meta:
            meta_text = json.dumps(image_meta, default=str).lower()
            if "swatch" in meta_text or "variant" in meta_text:
                return
        url = normalize_image_url(value)
        if is_product_image_url(url):
            urls.append(url)

    if isinstance(image_info, dict):
        for key in ("thumbnailUrl", "productImageUrl", "mainImageUrl", "url", "src"):
            add(image_info.get(key), image_info)
        for list_key in ("allImages", "images", "productImages"):
            for item in as_list(image_info.get(list_key)):
                if isinstance(item, dict):
                    for key in ("url", "src", "zoomable", "thumbnailUrl", "largeUrl"):
                        add(item.get(key), item)
                else:
                    add(item)
    elif isinstance(image_info, list):
        for item in image_info:
            if isinstance(item, dict):
                for key in ("url", "src", "zoomable", "thumbnailUrl", "largeUrl"):
                    add(item.get(key), item)
            else:
                add(item)
    else:
        add(image_info)

    return unique_images(urls)


def unique_images(urls: Iterable[str]) -> list[str]:
    seen: set[str] = set()
    output: list[str] = []
    for url in urls:
        # Deduplicate using the image path while keeping the first full URL.
        parsed = urlparse(url)
        key = f"{parsed.netloc.lower()}{parsed.path.lower()}"
        if key not in seen:
            seen.add(key)
            output.append(url)
    return output


def extract_images(product: dict[str, Any], json_ld: dict[str, Any]) -> tuple[str, str]:
    urls: list[str] = []

    # Strict source: product.imageInfo from PDP structured product data only.
    urls.extend(collect_image_urls_from_image_info(product.get("imageInfo")))

    # Secondary strict fallback: Product JSON-LD image field.
    if not urls and isinstance(json_ld, dict):
        urls.extend(collect_image_urls_from_image_info(json_ld.get("image")))

    # Last targeted fallback: direct product image fields, not global page regex.
    if not urls:
        for key in ("image", "images", "productImageUrl", "thumbnailUrl"):
            if key in product:
                urls.extend(collect_image_urls_from_image_info(product.get(key)))

    urls = unique_images(urls)
    main = urls[0] if urls else ""
    additional = " | ".join(urls[1:]) if len(urls) > 1 else ""
    return main, additional


def extract_bullets(product: dict[str, Any]) -> str:
    """Extract original PDP bullets only from structured PDP fields."""
    lines: list[str] = []

    # On Walmart PDPs, shortDescription commonly contains the original bullet list.
    for key in ("shortDescription", "keyFeatures", "features"):
        value = product.get(key)
        if value:
            lines.extend(html_to_lines(value))
            if lines:
                break

    return " | ".join(unique_keep_order(lines))


def extract_description(product: dict[str, Any], json_ld: dict[str, Any]) -> str:
    """Extract original PDP description. Never synthesize or summarize."""
    for key in ("longDescription", "description", "productDescription"):
        value = product.get(key)
        if value:
            lines = html_to_lines(value)
            text = compact_spaces(" ".join(lines))
            if text:
                return text

    # JSON-LD Product description is still original structured page data.
    text = clean_text(json_ld.get("description")) if isinstance(json_ld, dict) else ""
    return text


def parse_spec_pairs(value: Any) -> list[tuple[str, str]]:
    pairs: list[tuple[str, str]] = []

    if value is None:
        return pairs

    if isinstance(value, list):
        for item in value:
            pairs.extend(parse_spec_pairs(item))
        return pairs

    if isinstance(value, dict):
        # Common shapes: {name, value}, {displayName, values}, {key, value}
        name = clean_text(
            value.get("name")
            or value.get("displayName")
            or value.get("label")
            or value.get("key")
            or value.get("specName")
        )
        raw_val = (
            value.get("value")
            or value.get("values")
            or value.get("displayValue")
            or value.get("specValue")
            or value.get("text")
        )
        spec_value = clean_text(raw_val)
        if name and spec_value and name.lower() != spec_value.lower():
            pairs.append((name, spec_value))

        for nested_key in ("specifications", "productSpecifications", "attributes", "values"):
            nested = value.get(nested_key)
            if nested is not raw_val:
                pairs.extend(parse_spec_pairs(nested))
        return pairs

    return pairs


def extract_spec_pairs(product: dict[str, Any]) -> list[tuple[str, str]]:
    pairs: list[tuple[str, str]] = []
    for key in ("specifications", "productSpecifications", "attributes"):
        pairs.extend(parse_spec_pairs(product.get(key)))

    # Some Walmart product JSON nests specifications deeper inside product only.
    if not pairs:
        for path, key, value in recursive_key_values(product, ("specification", "specifications")):
            if path_has_terms(path, AI_PATH_TERMS):
                continue
            pairs.extend(parse_spec_pairs(value))

    seen: set[tuple[str, str]] = set()
    clean_pairs: list[tuple[str, str]] = []
    for name, value in pairs:
        if not name or not value:
            continue
        pair_key = (name.lower(), value.lower())
        if pair_key not in seen:
            seen.add(pair_key)
            clean_pairs.append((name, value))
    return clean_pairs


def extract_specifications(product: dict[str, Any]) -> str:
    pairs = extract_spec_pairs(product)
    return " | ".join(f"{name}: {value}" for name, value in pairs)


def extract_named_content(product: dict[str, Any], spec_pairs: list[tuple[str, str]], name_parts: Iterable[str]) -> str:
    wanted = tuple(part.lower() for part in name_parts)
    values: list[str] = []

    for name, value in spec_pairs:
        low_name = name.lower()
        if any(part in low_name for part in wanted):
            values.append(value)

    for path, key, value in recursive_key_values(product, wanted):
        if path_has_terms(path, AI_PATH_TERMS):
            continue
        text = clean_text(value)
        if text:
            values.append(text)

    return " | ".join(unique_keep_order(values))


def extract_category(product: dict[str, Any], json_ld: dict[str, Any]) -> str:
    for key in ("categoryPath", "category", "productCategory"):
        value = product.get(key)
        if isinstance(value, str):
            text = clean_text(value)
            if text:
                return text
        if isinstance(value, dict):
            for path_key in ("path", "name", "displayName"):
                text = clean_text(value.get(path_key))
                if text:
                    return text

    crumbs = product.get("breadCrumbs") or product.get("breadcrumbs")
    if isinstance(crumbs, list):
        names = []
        for crumb in crumbs:
            if isinstance(crumb, dict):
                names.append(clean_text(crumb.get("name") or crumb.get("label")))
            else:
                names.append(clean_text(crumb))
        names = [name for name in names if name]
        if names:
            return " > ".join(names)

    json_category = clean_text(json_ld.get("category")) if isinstance(json_ld, dict) else ""
    return json_category


def extract_upc_gtin(product: dict[str, Any], json_ld: dict[str, Any]) -> str:
    values: list[str] = []
    for key in ("upc", "UPC", "gtin", "gtin8", "gtin12", "gtin13", "gtin14"):
        text = clean_text(product.get(key) or (json_ld.get(key) if isinstance(json_ld, dict) else ""))
        if text:
            values.append(text)

    if not values:
        for path, key, value in recursive_key_values(product, ("upc", "gtin")):
            text = clean_text(value)
            if text:
                values.append(text)
    return " | ".join(unique_keep_order(values))


def extract_model(product: dict[str, Any]) -> str:
    values: list[str] = []
    for key in ("model", "modelNumber", "manufacturerPartNumber", "mpn", "partNumber"):
        text = clean_text(product.get(key))
        if text:
            values.append(text)
    if not values:
        for path, key, value in recursive_key_values(product, ("modelnumber", "manufacturernumber", "partnumber", "mpn")):
            text = clean_text(value)
            if text:
                values.append(text)
    return " | ".join(unique_keep_order(values))


def build_output_row(
    sku: str,
    url: str,
    item_id: str,
    status: str,
    error: str,
    selected_fields: Iterable[str],
    data: dict[str, str] | None = None,
) -> dict[str, str]:
    row = {
        "SKU": str(sku or ""),
        "Walmart URL": str(url or ""),
        "Walmart Item ID": str(item_id or ""),
        "Status": status,
        "Error": error,
    }
    data = data or {}
    for field_key in selected_fields:
        label = FIELD_LABELS.get(field_key, field_key)
        row[label] = data.get(field_key, "")
    return row


def scrape_walmart_product(
    sku: str,
    url: str,
    selected_fields: Iterable[str] | None = None,
    timeout: int = 25,
    session: requests.Session | None = None,
) -> dict[str, str]:
    """Scrape one Walmart PDP URL and return a flat row for export.

    The function intentionally returns blank values when original structured PDP
    data is unavailable. It does not infer, generate, or summarize missing data.
    """
    selected = list(selected_fields or FIELD_KEYS)
    item_id = extract_item_id(url)

    if not is_valid_walmart_url(url):
        return build_output_row(sku, url, item_id, "Invalid URL", "URL must be a walmart.com http(s) product URL.", selected)

    http = session or requests.Session()
    try:
        response = http.get(url, headers=DEFAULT_HEADERS, timeout=timeout)
    except requests.RequestException as exc:
        return build_output_row(sku, url, item_id, "Failed", f"Request error: {exc}", selected)

    status_code = response.status_code
    if status_code == 404:
        return build_output_row(sku, url, item_id, "Not Found", "HTTP 404", selected)
    if status_code in {401, 403, 407, 429}:
        return build_output_row(sku, url, item_id, "Blocked", f"HTTP {status_code}", selected)
    if status_code >= 400:
        return build_output_row(sku, url, item_id, "Failed", f"HTTP {status_code}", selected)

    html = response.text or ""
    low_html = html[:5000].lower()
    if any(pattern in low_html for pattern in BLOCK_TEXT_PATTERNS):
        return build_output_row(sku, url, item_id, "Blocked", "Page returned bot/verification content.", selected)

    soup = BeautifulSoup(html, "html.parser")
    page_text = soup.get_text(" ", strip=True)
    next_data, json_ld_products = load_page_json(soup)
    product = find_product_object(next_data)
    json_ld = json_ld_products[0] if json_ld_products else {}

    if not item_id:
        item_id = clean_text(first_value(product, ("usItemId", "productId", "itemId", "id")))

    extraction_warning = ""
    if not product and not json_ld:
        # h1 fallback is allowed only for title-like basic data; content fields stay blank.
        extraction_warning = "Structured product data not found; returned limited values only."

    data: dict[str, str] = {}

    title = clean_text(first_value(product, ("name", "title", "productName")))
    if not title and isinstance(json_ld, dict):
        title = clean_text(json_ld.get("name"))
    if not title:
        h1 = soup.find("h1")
        title = clean_text(h1.get_text(" ", strip=True)) if h1 else ""

    brand = clean_text(first_value(product, ("brand", "brandName")))
    if isinstance(product.get("brand"), dict):
        brand = clean_text(product["brand"].get("name"))
    if not brand and isinstance(json_ld.get("brand") if isinstance(json_ld, dict) else None, dict):
        brand = clean_text(json_ld["brand"].get("name"))
    elif not brand and isinstance(json_ld, dict):
        brand = clean_text(json_ld.get("brand"))

    rating, review_count = extract_rating(product, json_ld if isinstance(json_ld, dict) else {})
    main_image, additional_images = extract_images(product, json_ld if isinstance(json_ld, dict) else {})
    spec_pairs = extract_spec_pairs(product)

    extracted_values = {
        "title": title,
        "brand": brand,
        "price": extract_price(product, json_ld if isinstance(json_ld, dict) else {}),
        "currency": extract_currency(product, json_ld if isinstance(json_ld, dict) else {}),
        "seller": extract_seller(product, json_ld if isinstance(json_ld, dict) else {}),
        "availability": extract_availability(product, json_ld if isinstance(json_ld, dict) else {}, page_text),
        "rating": rating,
        "review_count": review_count,
        "main_image": main_image,
        "additional_images": additional_images,
        "bullet_points": extract_bullets(product),
        "description": extract_description(product, json_ld if isinstance(json_ld, dict) else {}),
        "specifications": " | ".join(f"{name}: {value}" for name, value in spec_pairs),
        "ingredients": extract_named_content(product, spec_pairs, ("ingredient", "ingredients")),
        "warnings": extract_named_content(product, spec_pairs, ("warning", "warnings", "caution", "prop65")),
        "category": extract_category(product, json_ld if isinstance(json_ld, dict) else {}),
        "upc_gtin": extract_upc_gtin(product, json_ld if isinstance(json_ld, dict) else {}),
        "model": extract_model(product),
    }

    for field_key in selected:
        data[field_key] = extracted_values.get(field_key, "")

    non_empty_selected_values = [value for value in data.values() if value]
    status = "Success" if non_empty_selected_values else "Partial"
    error = extraction_warning if extraction_warning else ""
    if status == "Partial" and not error:
        error = "Selected fields were not found in original structured PDP data."

    return build_output_row(sku, url, item_id, status, error, selected, data)
